name: Publish Site

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: true

      # Install Node.js (latest LTS version)
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts"

      # Step 2: Set up Hugo
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3.0.0

      # Build the site with Hugo
      - name: Build Site with Hugo
        run: |
          hugo npx pagefind --site public

      # Deploy to GitHub Pages for Dev Branch
      - name: Deploy to GitHub Pages (Dev)
        if: github.ref == 'refs/heads/dev'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          cname: packages.rizin.re
